language: csharp
mono: none

env:
  matrix:
    - REGION=va
    - REGION=ca

before_install:
  # Install .NET 7.0 SDK using Microsoft's official script
  - wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
  - chmod +x dotnet-install.sh
  - ./dotnet-install.sh --channel 7.0 --install-dir $HOME/.dotnet
  - export PATH="$HOME/.dotnet:$PATH"
  - export DOTNET_ROOT="$HOME/.dotnet"
  - dotnet --version
  # Login to docker hub
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

script:
- dotnet build
- dotnet test LearnositySDKUnitTests/LearnositySDKUnitTests.csproj
- dotnet test LearnositySDKIntegrationTests/LearnositySDKIntegrationTests.csproj

notifications:
  slack:
    rooms:
      secure: OFrn7jLLe/14eIZWYsoRn+66v2k8qN9KXKP4of8yiL5QjDmKhDvUPCB6PHi0FOLQnzjPqXaASRYJkor0EADsUMbsaEVLJoQpZs4ta3iwC5PhTlyVStiXHaSWqIkgnX7mg1LDoC/wcpQLN9fm+kmDxIYRMBQ3EPKye9tR3Ro5Hsk=
    on_success: change
