language: csharp
mono: none
dotnet: 3.1

env:
  matrix:
    - REGION=va
    - REGION=ca
    
before_install:
  # Login to docker hub
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

script:
- dotnet build
- dotnet test LearnositySDKUnitTests/LearnositySDKUnitTests.csproj
- dotnet test LearnositySDKIntegrationTests/LearnositySDKIntegrationTests.csproj

notifications:
  slack:
    rooms:
      secure: OFrn7jLLe/14eIZWYsoRn+66v2k8qN9KXKP4of8yiL5QjDmKhDvUPCB6PHi0FOLQnzjPqXaASRYJkor0EADsUMbsaEVLJoQpZs4ta3iwC5PhTlyVStiXHaSWqIkgnX7mg1LDoC/wcpQLN9fm+kmDxIYRMBQ3EPKye9tR3Ro5Hsk=
    on_success: change
